services:
    # FastAPI backend service
    backend:
        build:
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - ./uploads:/app/uploads # Mount uploads volume
            - ./models:/app/models # Mount models volume
        ports:
            - "7135:7135" # Expose FastAPI app on port 7135
        environment:
            - PYTHONUNBUFFERED=1 # To prevent Python output buffering (useful for logging)
        networks:
            - app-network

    # Next.js frontend service
    frontend:
        build:
            context: ./poxapp
            dockerfile: Dockerfile
        environment:
            - DATABASE_URL=mysql://root:fadifadi2025@mysql:3306/skinconditions
            - PORT=7134
            - HOST=0.0.0.0
        depends_on:
            - mysql
        volumes:
            - ./poxapp:/app
            # prevent host bind mount from hiding container deps:
            - /app/node_modules
        ports:
            - "7134:7134"
        working_dir: /app
        command: ["sh","-lc","npx next dev -p $PORT -H $HOST"]
        networks:
            - app-network

    # MySQL service
    mysql:
        image: mysql:8.0 # Use official MySQL image, version 8.0
        environment:
            MYSQL_ROOT_PASSWORD: fadifadi2025 # Replace with a secure password
            MYSQL_DATABASE: skinconditions # Default database name (optional)
            MYSQL_USER: dux # Optional: create a custom MySQL user
            MYSQL_PASSWORD: dux123 # Optional: password for custom user
        ports:
            - "7136:3306" # Map MySQL port 3306 to 7136
        volumes:
            - mysql-data:/var/lib/mysql # Persist MySQL data
        networks:
            - app-network

volumes:
    uploads:
        driver: local
    models:
        driver: local
    mysql-data:
        driver: local

# Network for the services to communicate
networks:
    app-network:
        driver: bridge
